url: "https://onepiecesoftware.github.io"
force-https: True

# HTML Head
lang: "en"
author: "Jendrik Johannes"
title: "onepiece.Software"
description: "onepiece.Software – by Jendrik Johannes"
favicon: "/img/favicon.png"

# Color the browser elements
color-browser: "#000000"
apple-status-bar-style: "black"

# Sections shown in the index page
pages_list:
  Developer Productivity: 'dev-prod'
  Game Development: 'game-dev'
  Software Reuse: 'software-reuse'

# Exclusion list from the generated _site
exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

sass:
  style: compressed

gems:
  - jemoji
